#!/bin/bash

if pacman -Q nautilus &>/dev/null; then
  echo "Nautilus is already installed: $(pacman -Q npacman -Q alacrittypacman -Q alacritty-gitautilus)"
else
  echo "Nautilus not found. Installing..."
  sudo pacman -S --noconfirm nautilus
  echo "Nautilus installed successfully."
fi

yay -S nautilus-open-any-terminal
