#!/bin/bash

# Install if missing
if ! command -v alacritty >/dev/null; then
    echo "Installing alacritty..."
    sudo pacman -S --noconfirm alacritty
fi

if ! command -v wiremix >/dev/null; then
    echo "Installing wiremix..."
    yay -S --noconfirm wiremix
fi
