[server]
show_percentage = true
max_volume = 100
style = "./style.css"
playerctl_format = "Player"

## set format for the media player OSD
# playerctl_format = "{artist} - {title}"
## Available values:
## artist, albumArtist, title, album, trackNumber, discNumber, autoRating

