return {
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = {
			-- "nvim-treesitter/nvim-treesitter-textobjects",
			-- "nvim-treesitter/nvim-tree-docs",
			-- "nvim-treesitter/playground",
		},
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter").setup({
				-- Directory to install parsers and queries to (prepended to `runtimepath` to have priority)
				install_dir = vim.fn.stdpath("data") .. "/site",
			})
			require("nvim-treesitter").install({
				"ada",
				"agda",
				"angular",
				"apex",
				"arduino",
				"asm",
				"astro",
				"authzed",
				"awk",
				"bash",
				"bass",
				"beancount",
				"bibtex",
				"bicep",
				"bitbake",
				-- "blade",
				"c",
				"c_sharp",
				"cairo",
				"capnp",
				"chatito",
				"clojure",
				"cmake",
				"comment",
				"commonlisp",
				"cooklang",
				"corn",
				"cpon",
				"cpp",
				"css",
				"csv",
				"cuda",
				"cue",
				"d",
				"dart",
				"devicetree",
				"dhall",
				"diff",
				"disassembly",
				"djot",
				"dockerfile",
				"dot",
				"doxygen",
				"dtd",
				"earthfile",
				"ebnf",
				"editorconfig",
				"eds",
				"eex",
				"elixir",
				"elm",
				"elsa",
				"elvish",
				"embedded_template",
				"erlang",
				"facility",
				"faust",
				"fennel",
				"fidl",
				"firrtl",
				"fish",
				"foam",
				"forth",
				"fortran",
				"fsh",
				"fsharp",
				"func",
				"gdshader",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"gleam",
				"glimmer_javascript",
				"glimmer_typescript",
				"glsl",
				"gn",
				"gnuplot",
				"go",
				"goctl",
				"godot_resource",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"gpg",
				"graphql",
				"gren",
				"groovy",
				"gstlaunch",
				"hack",
				"hare",
				"haskell",
				"haskell_persistent",
				"hcl",
				"heex",
				"helm",
				"hjson",
				"hlsl",
				"hlsplaylist",
				"hocon",
				"hoon",
				"html",
				"htmldjango",
				"http",
				"hurl",
				"hyprlang",
				"idl",
				"ini",
				"inko",
				"ispc",
				"janet_simple",
				"java",
				"javascript",
				"jq",
				"jsdoc",
				"json",
				"json5",
				"jsonnet",
				"julia",
				"just",
				"kconfig",
				"kdl",
				"kotlin",
				"koto",
				"kusto",
				"lalrpop",
				-- "latex", -- error
				"ledger",
				"leo",
				"linkerscript",
				"liquid",
				"liquidsoap",
				"llvm",
				"lua",
				"luadoc",
				"luap",
				"luau",
				"m68k",
				"make",
				"markdown",
				"markdown_inline",
				"matlab",
				"menhir",
				"mermaid",
				"meson",
				-- "mlir", -- error
				"muttrc",
				"nasm",
				"nginx",
				"nickel",
				"nim",
				"nim_format_string",
				"ninja",
				"nix",
				"nqc",
				"objc",
				"objdump",
				"ocaml",
				"ocaml_interface",
				-- "ocamllex", -- error
				"odin",
				"pascal",
				"passwd",
				"pem",
				-- "perl", -- error
				"php",
				"php_only",
				"phpdoc",
				"pioasm",
				"po",
				"pod",
				"pony",
				"powershell",
				"printf",
				"prisma",
				"problog",
				"prolog",
				"promql",
				"properties",
				"proto",
				"prql",
				"psv",
				"pug",
				"puppet",
				"purescript",
				"pymanifest",
				"python",
				"ql",
				"qmldir",
				"qmljs",
				"query",
				"r",
				"racket",
				"ralph",
				"rasi",
				"rbs",
				"re2c",
				"readline",
				"regex",
				"rego",
				"requirements",
				"rescript",
				"rnoweb",
				"ron",
				"rst",
				"ruby",
				"rust",
				"scala",
				-- "scfg", -- error
				"scheme",
				"scss",
				"slang",
				"smali",
				"smithy",
				"snakemake",
				-- "snl", -- error
				"solidity",
				"soql",
				"sosl",
				"sourcepawn",
				"sparql",
				-- "sproto", -- error
				"sql",
				"squirrel",
				"ssh_config",
				"starlark",
				"strace",
				"styled",
				"supercollider",
				"superhtml",
				"surface",
				"svelte",
				-- "sway", -- error
				-- "swift",
				"sxhkdrc",
				"systemtap",
				-- "systemverilog", -- error
				"t32",
				"tablegen",
				"tact",
				"tcl",
				-- "teal", -- error
				"templ",
				-- "tera", -- error
				"terraform",
				"textproto",
				"thrift",
				"tiger",
				"tlaplus",
				"tmux",
				"todotxt",
				"toml",
				"tsv",
				"tsx",
				"turtle",
				"twig",
				"typescript",
				"typespec",
				"typoscript",
				"typst",
				"udev",
				"ungrammar",
				-- "unison", -- error
				"usd",
				"uxntal",
				"v",
				"vala",
				"vhdl",
				"vhs",
				"vim",
				"vimdoc",
				"vrl",
				"vue",
				"wgsl",
				"wgsl_bevy",
				"wing",
				"wit",
				-- "wxml", -- error
				"xcompose",
				"xml",
				"xresources",
				"yaml",
				"yang",
				"yuck",
				"zathurarc",
				"zig",
			})
			-- require("nvim-treesitter.configs").setup({
			-- tree_docs = {enable = true},
			-- A list of parser names, or "all" (the five listed parsers should always be installed)
			-- ensure_installed = {
			-- "ada",
			-- "agda",
			-- "angular",
			-- "apex",
			-- "arduino",
			-- "asm",
			-- "astro",
			-- "authzed",
			-- "awk",
			-- "bash",
			-- "bass",
			-- "beancount",
			-- "bibtex",
			-- "bicep",
			-- "bitbake",
			-- "c",
			-- "c_sharp",
			-- "cairo",
			-- "capnp",
			-- "chatito",
			-- "clojure",
			-- "cmake",
			-- "comment",
			-- "commonlisp",
			-- "cooklang",
			-- "corn",
			-- "cpon",
			-- "cpp",
			-- "css",
			-- "csv",
			-- "cuda",
			-- "cue",
			-- "d",
			-- "dart",
			-- "devicetree",
			-- "dhall",
			-- "diff",
			-- "disassembly",
			-- "djot",
			-- "dockerfile",
			-- "dot",
			-- "doxygen",
			-- "dtd",
			-- "earthfile",
			-- "ebnf",
			-- "editorconfig",
			-- "eds",
			-- "eex",
			-- "elixir",
			-- "elm",
			-- "elsa",
			-- "elvish",
			-- "embedded_template",
			-- "erlang",
			-- "facility",
			-- "faust",
			-- "fennel",
			-- "fidl",
			-- "firrtl",
			-- "fish",
			-- "foam",
			-- "forth",
			-- "fortran",
			-- "fsh",
			-- "fsharp",
			-- "func",
			-- "gdshader",
			-- "git_config",
			-- "git_rebase",
			-- "gitattributes",
			-- "gitcommit",
			-- "gitignore",
			-- "gleam",
			-- "glimmer_javascript",
			-- "glimmer_typescript",
			-- "glsl",
			-- "gn",
			-- "gnuplot",
			-- "go",
			-- "goctl",
			-- "godot_resource",
			-- "gomod",
			-- "gosum",
			-- "gotmpl",
			-- "gowork",
			-- "gpg",
			-- "graphql",
			-- "gren",
			-- "groovy",
			-- "gstlaunch",
			-- "hack",
			-- "hare",
			-- "haskell",
			-- "haskell_persistent",
			-- "hcl",
			-- "heex",
			-- "helm",
			-- "hjson",
			-- "hlsl",
			-- "hlsplaylist",
			-- "hocon",
			-- "hoon",
			-- "html",
			-- "htmldjango",
			-- "http",
			-- "hurl",
			-- "hyprlang",
			-- "idl",
			-- "ini",
			-- "inko",
			-- "ispc",
			-- "janet_simple",
			-- "java",
			-- "javascript",
			-- "jq",
			-- "jsdoc",
			-- "json",
			-- "json5",
			-- "jsonnet",
			-- "julia",
			-- "just",
			-- "kconfig",
			-- "kdl",
			-- "kotlin",
			-- "koto",
			-- "kusto",
			-- "lalrpop",
			-- -- "latex", -- error
			-- "ledger",
			-- "leo",
			-- "linkerscript",
			-- "liquid",
			-- "liquidsoap",
			-- "llvm",
			-- "lua",
			-- "luadoc",
			-- "luap",
			-- "luau",
			-- "m68k",
			-- "make",
			-- "markdown",
			-- "markdown_inline",
			-- "matlab",
			-- "menhir",
			-- "mermaid",
			-- "meson",
			-- -- "mlir", -- error
			-- "muttrc",
			-- "nasm",
			-- "nginx",
			-- "nickel",
			-- "nim",
			-- "nim_format_string",
			-- "ninja",
			-- "nix",
			-- "nqc",
			-- "objc",
			-- "objdump",
			-- "ocaml",
			-- "ocaml_interface",
			-- -- "ocamllex", -- error
			-- "odin",
			-- "pascal",
			-- "passwd",
			-- "pem",
			-- -- "perl", -- error
			-- "php",
			-- "php_only",
			-- "phpdoc",
			-- "pioasm",
			-- "po",
			-- "pod",
			-- "pony",
			-- "powershell",
			-- "printf",
			-- "prisma",
			-- "problog",
			-- "prolog",
			-- "promql",
			-- "properties",
			-- "proto",
			-- "prql",
			-- "psv",
			-- "pug",
			-- "puppet",
			-- "purescript",
			-- "pymanifest",
			-- "python",
			-- "ql",
			-- "qmldir",
			-- "qmljs",
			-- "query",
			-- "r",
			-- "racket",
			-- "ralph",
			-- "rasi",
			-- "rbs",
			-- "re2c",
			-- "readline",
			-- "regex",
			-- "rego",
			-- "requirements",
			-- "rescript",
			-- "rnoweb",
			-- "ron",
			-- "rst",
			-- "ruby",
			-- "rust",
			-- "scala",
			-- -- "scfg", -- error
			-- "scheme",
			-- "scss",
			-- "slang",
			-- "smali",
			-- "smithy",
			-- "snakemake",
			-- -- "snl", -- error
			-- "solidity",
			-- "soql",
			-- "sosl",
			-- "sourcepawn",
			-- "sparql",
			-- -- "sproto", -- error
			-- "sql",
			-- "squirrel",
			-- "ssh_config",
			-- "starlark",
			-- "strace",
			-- "styled",
			-- "supercollider",
			-- "superhtml",
			-- "surface",
			-- "svelte",
			-- -- "sway", -- error
			-- -- "swift",
			-- "sxhkdrc",
			-- "systemtap",
			-- -- "systemverilog", -- error
			-- "t32",
			-- "tablegen",
			-- "tact",
			-- "tcl",
			-- -- "teal", -- error
			-- "templ",
			-- -- "tera", -- error
			-- "terraform",
			-- "textproto",
			-- "thrift",
			-- "tiger",
			-- "tlaplus",
			-- "tmux",
			-- "todotxt",
			-- "toml",
			-- "tsv",
			-- "tsx",
			-- "turtle",
			-- "twig",
			-- "typescript",
			-- "typespec",
			-- "typoscript",
			-- "typst",
			-- "udev",
			-- "ungrammar",
			-- -- "unison", -- error
			-- "usd",
			-- "uxntal",
			-- "v",
			-- "vala",
			-- "vhdl",
			-- "vhs",
			-- "vim",
			-- "vimdoc",
			-- "vrl",
			-- "vue",
			-- "wgsl",
			-- "wgsl_bevy",
			-- "wing",
			-- "wit",
			-- -- "wxml", -- error
			-- "xcompose",
			-- "xml",
			-- "xresources",
			-- "yaml",
			-- "yang",
			-- "yuck",
			-- "zathurarc",
			-- "zig",
			-- },

			-- -- Install parsers synchronously (only applied to `ensure_installed`)
			-- sync_install = false,

			-- -- Automatically install missing parsers when entering buffer
			-- -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
			-- auto_install = true,
			-- indent = {
			-- 	enable = true,
			-- },
			-- highlight = {
			-- 	enable = true,

			-- 	-- Setting this to true will run `:h syntax` and tree-sitter at the same time.
			-- 	-- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
			-- 	-- Using this option may slow down your editor, and you may see some duplicate highlights.
			-- 	-- Instead of true it can also be a list of languages
			-- 	additional_vim_regex_highlighting = { "markdown" },
			-- },
			-- })

			-- local treesitter_parser_config = require("nvim-treesitter.parsers")
			-- treesitter_parser_config.templ = {
			-- 	install_info = {
			-- 		url = "https://github.com/vrischmann/tree-sitter-templ.git",
			-- 		files = { "src/parser.c", "src/scanner.c" },
			-- 		branch = "master",
			-- 	},
			-- }

			-- treesitter_parser_config.blade = {
			-- 	install_info = {
			-- 		url = "https://github.com/EmranMR/tree-sitter-blade",
			-- 		files = { "src/parser.c" },
			-- 		branch = "main",
			-- 	},
			-- 	filetype = "blade",
			-- }


			vim.filetype.add({
				pattern = {
					[".*%.blade%.php"] = "blade",
				},
			})

            vim.api.nvim_create_autocmd("FileType", {
                pattern = "*",
                callback = function()
                    pcall(vim.treesitter.start)  -- pcall so it silently fails if no parser exists
                    vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
                end,
            })

            vim.treesitter.language.register('bash', 'env')
			vim.treesitter.language.register("templ", "templ")
		end,
	},
	{
		"nvim-treesitter/nvim-treesitter-refactor",
		dependencies = { "nvim-treesitter/nvim-treesitter" },
		lazy = true, -- prevents the plugin/ vimscript from auto-sourcing early
	},
}
